apiVersion: v1
kind: Service
metadata:
  name: tickets-mongo-srv
spec:
  type: ClusterIP
  selector:
    app: tickets-mongo
  ports:
  - port: 27017
    protocol: TCP
    name: db
    targetPort: 27017
